name: Continuous Integration
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # The line below is a simplifier to use Yarn, made by the community
      # It seems it's not so easy to work with Caches
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install
      - run: yarn test
